### ISSUE TITLE
'no-duplicate-http-in-urls' detects 

### ISSUE THREAD

**Issue by ba47-development** [node-red/nrlint#31]
### Current Behavior

detecting duplicates is a great function of **nrLint**.

But it is common use, that the same URL will be used multiple times with different methods, e.g. for GET, POST, PUT, DELETE, etc. nrLint detects these as duplicates, but in fact they are not.

Here, all calls are names "/demo", but with different methods:
![grafik](https://user-images.githubusercontent.com/30465884/169286663-bfec0868-336b-4feb-b9da-ddaa913afa56.png)

### Expected Behavior

Methods must be taken into account as well to identify duplicates.

**Comment by knolleary** [comment]
Duplicate of #19 - the fix has been in the code for sometime, but it hasn't been released yet.

We will get a new version published once we have resolved #30

**Comment by ba47-development** [comment]
Yes, true, my beta was #1. Ok, cool, that it's fixed!  :-)
