### ISSUE TITLE
Linting error when adding junction to wire

### ISSUE THREAD

**Issue by My-Random-Thoughts** [node-red/nrlint#32]
### Current Behavior

When adding a junction to a wire between two nodes that are close together, a linting error occurs suggesting that nodes are overlapping

### Expected Behavior

No linting error at all

### Steps To Reproduce

Add any two nodes, 4 units apart - Inject and Debug
Join them with a wire
Select wire
Right-click, Insert, Junction

### Example flow

BEFORE JUNCTION:

`[{"id":"633ae00f2207bd45","type":"inject","z":"4d4c501eae52f7b1","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":380,"y":160,"wires":[["3cf4a9d4fc84816a"]]},{"id":"3cf4a9d4fc84816a","type":"debug","z":"4d4c501eae52f7b1","name":"debug 1","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":580,"y":160,"wires":[]}]`

AFTER JUNCTION

`[{"id":"633ae00f2207bd45","type":"inject","z":"4d4c501eae52f7b1","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":380,"y":160,"wires":[["551478f72fdb7c0c"]]},{"id":"3cf4a9d4fc84816a","type":"debug","z":"4d4c501eae52f7b1","name":"debug 1","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":580,"y":160,"wires":[]},{"id":"551478f72fdb7c0c","type":"junction","z":"4d4c501eae52f7b1","x":480,"y":160,"wires":[["3cf4a9d4fc84816a"]]}]`

### Environment

- Node-RED version: 3.0.0-beta.4
- Node.js version: v18.4.0
- npm version: 8.12.1
- Platform/OS: Linux 5.13.0-52-generic x86_64
- Browser: Firefox 102

**Comment by My-Random-Thoughts** [comment]
I am not 100% sure it's a linting issue per-se, as if you move the nodes apart, the overlapping message disappears

**Comment by m-schaeffler** [comment]
For me it looks like this: The junction is calculated with the size of a normal node and so it overlaps, if to near to another node.
